package ca.nl.cna.cp3566.store;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * INFRASTRUCTURE (given — read it, you do not have to change it).
 *
 * ============================================================================
 *  MINIMAL CSV READER  +  ASOS DATA CLEAN-UP
 * ============================================================================
 *
 * This is the "how do I read a CSV in plain Java" example for the lab. It reads
 * the real ASOS dataset (products_asos.csv, in the project root) and turns it
 * into clean {@link Product} rows the database can store. {@link Database} calls
 * load() once, the first time the server starts.
 *
 * WHY a hand-written reader instead of split(","): the file is real-world messy.
 * Fields are quoted, and the quoted fields contain commas, embedded newlines,
 * and doubled "" quotes (the description column is a whole JSON blob). A naive
 * line.split(",") would shred those rows. The small state machine in CsvReader
 * (bottom of this file) follows the CSV rules (RFC 4180): inside quotes, commas
 * and newlines are just text, and "" means one literal quote.
 *
 * The dataset has no clean category, no id, and no rating, so this class:
 *   - assigns ids 1..N as rows are accepted,
 *   - DERIVES a tidy category from keywords in the product name,
 *   - parses the price and skips rows that have none,
 *   - pulls the first real image URL out of the images column,
 *   - synthesises a stable star rating from the id,
 *   - derives stock from the in-stock sizes (every 37th product forced to 0 so
 *     the "sold out" 409 path always has something to hit),
 *   - de-duplicates colour/URL variants by SKU and keeps the first {@value #LIMIT}.
 *
 * You consume the result; you do not edit this file. (If you wanted to, the
 * obvious extension points are categoryFor(...) and stockFor(...).)
 */
public final class CsvProductSource {

    /** Where the CSV lives, relative to the project root (the run directory). */
    public static final String CSV_PATH = "products_asos.csv";

    /** Keep the catalogue a sensible size (~5000), like a small real store. */
    public static final int LIMIT = 5000;

    /** A loaded product plus the stock we worked out for it. */
    public record SeedProduct(Product product, int stock) { }

    private CsvProductSource() { }

    /** Read and clean the CSV into at most {@link #LIMIT} seed products. */
    public static List<SeedProduct> load() {
        Path path = Path.of(CSV_PATH);
        if (!Files.isReadable(path)) {
            throw new IllegalStateException(
                    "Could not find " + CSV_PATH + " in the project root (" +
                    path.toAbsolutePath() + "). The ASOS dataset must be there to seed the store.");
        }

        List<SeedProduct> out = new ArrayList<>();
        Set<String> seenSkus = new HashSet<>();
        int nextId = 1;

        // try-with-resources: the reader is closed automatically, even on error.
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8);
             CsvReader csv = new CsvReader(reader)) {

            // First record is the header row. Find each column by name so we do
            // not depend on column ORDER:
            //   url,name,size,category,price,color,sku,description,images
            List<String> header = csv.next();
            if (header == null) throw new IllegalStateException(CSV_PATH + " is empty.");
            int iName   = header.indexOf("name");
            int iSize   = header.indexOf("size");
            int iPrice  = header.indexOf("price");
            int iColor  = header.indexOf("color");
            int iSku    = header.indexOf("sku");
            int iImages = header.indexOf("images");

            // Then read data rows until we have enough clean products.
            List<String> row;
            while ((row = csv.next()) != null && out.size() < LIMIT) {
                String name  = get(row, iName);
                String sku   = get(row, iSku);
                Double price = parsePrice(get(row, iPrice));

                if (name.isBlank() || price == null) continue;       // skip junk rows
                if (!sku.isBlank() && !seenSkus.add(sku)) continue;   // skip duplicate variants

                int id = nextId++;
                String color       = get(row, iColor);
                String category    = categoryFor(name);
                String description = buildDescription(name, color);
                String image       = imageFor(id, get(row, iImages));
                Rating rating      = syntheticRating(id);
                int stock          = stockFor(id, get(row, iSize));

                Product p = new Product(id, name, category, price, description, image, rating);
                out.add(new SeedProduct(p, stock));
            }
        } catch (IOException e) {
            throw new IllegalStateException("Failed reading " + CSV_PATH, e);
        }
        return out;
    }

    // ---- field clean-up helpers --------------------------------------------

    private static String get(List<String> row, int i) {
        return (i >= 0 && i < row.size() && row.get(i) != null) ? row.get(i).trim() : "";
    }

    private static Double parsePrice(String raw) {
        if (raw == null || raw.isBlank()) return null;
        try {
            double v = Double.parseDouble(raw.trim());
            return v > 0 ? v : null;
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Map keywords in the product name to a tidy clothing category. ORDER MATTERS
     * (check "t-shirt" before "shirt"; check "jean" before "boot" so bootcut jeans
     * do not become shoes). Unmatched names fall through to "Other".
     */
    static String categoryFor(String name) {
        String n = name.toLowerCase();
        if (anyOf(n, "jacket", "coat", "blazer", "gilet", "parka", "anorak", "bomber")) return "Coats & Jackets";
        if (anyOf(n, "dress", "playsuit", "jumpsuit")) return "Dresses";
        if (anyOf(n, "jean", "denim")) return "Jeans";
        if (anyOf(n, "jogger", "tracksuit", "training", "sport", "gym", "active", "legging", "running")) return "Activewear";
        if (anyOf(n, "hoodie", "sweatshirt", "sweat")) return "Hoodies & Sweatshirts";
        if (anyOf(n, "jumper", "knit", "cardigan")) return "Knitwear";
        if (anyOf(n, "trouser", "chino", "pant", "cargo")) return "Trousers";
        if (anyOf(n, "short")) return "Shorts";
        if (anyOf(n, "skirt")) return "Skirts";
        if (anyOf(n, "swim", "bikini", "trunk")) return "Swimwear";
        if (anyOf(n, "suit")) return "Suits";
        if (anyOf(n, "shoe", "trainer", "boot", "sneaker", "sandal", "heel", "loafer", "plimsoll")) return "Shoes";
        if (anyOf(n, "t-shirt", "tee", "vest", "top", "blouse", "cami", "bodysuit")) return "Tops";
        if (anyOf(n, "shirt")) return "Shirts";
        if (anyOf(n, "bag", "belt", "hat", "cap", "scarf", "sock", "glove", "sunglass",
                     "watch", "jewel", "necklace", "earring", "ring", "beanie", "wallet", "backpack")) return "Accessories";
        return "Other";
    }

    private static boolean anyOf(String haystack, String... needles) {
        for (String n : needles) if (haystack.contains(n)) return true;
        return false;
    }

    private static String buildDescription(String name, String color) {
        return color.isBlank() ? name + "." : name + " — colour: " + color + ".";
    }

    /** Folder where ImageDownloader stores the local copies, web-served at /images. */
    private static final Path LOCAL_IMAGE_DIR = Path.of("src", "main", "resources", "web", "images");

    /**
     * The image to show for this product. If ImageDownloader has already saved a
     * LOCAL copy (src/main/resources/web/images/&lt;id&gt;.jpg, served at
     * /images/&lt;id&gt;.jpg), use that so the store needs no network. Otherwise
     * fall back to the remote ASOS URL from the CSV (or a placeholder).
     */
    private static String imageFor(int id, String imagesCell) {
        if (Files.exists(LOCAL_IMAGE_DIR.resolve(id + ".jpg"))) {
            return "/images/" + id + ".jpg";
        }
        return firstImageUrl(imagesCell, id);
    }

    private static final Pattern IMG = Pattern.compile("https?://[^'\"\\s\\]]+");

    /** Pull the first image URL out of the images list-string, or fall back. */
    private static String firstImageUrl(String imagesCell, int id) {
        if (imagesCell != null && !imagesCell.isBlank()) {
            Matcher m = IMG.matcher(imagesCell);
            if (m.find()) return m.group();
        }
        return "https://picsum.photos/seed/asos-" + id + "/300/300";
    }

    /**
     * The dataset has no ratings, so derive a stable one from the id: a rate in
     * 3.0..5.0 and a plausible review count. Deterministic, so every run sees the
     * same numbers.
     */
    private static Rating syntheticRating(int id) {
        double rate = 3.0 + ((id * 7) % 21) / 10.0;     // 3.0 .. 5.0 in 0.1 steps
        int count = 5 + (id * 13) % 800;                // 5 .. 804
        return new Rating(Math.round(rate * 10.0) / 10.0, count);
    }

    /**
     * Stock from the in-stock sizes ("UK 12 - Out of stock" does not count),
     * scaled up so quantities above 1 are buyable. Every 37th product is forced
     * out of stock so the 409 (sold out) path always has something to hit.
     */
    private static int stockFor(int id, String sizeCell) {
        if (id % 37 == 0) return 0;
        int available = 0;
        for (String token : sizeCell.split(",")) {
            String t = token.trim().toLowerCase();
            if (!t.isEmpty() && !t.contains("out of stock")) available++;
        }
        return Math.max(1, available * 3);
    }

    // ---- the minimal RFC-4180 CSV reader -----------------------------------

    /**
     * A tiny streaming CSV reader. It returns one record at a time as a list of
     * fields, and correctly handles:
     *   - quoted fields:           "a,b"        -> one field: a,b
     *   - escaped quotes:          "she said ""hi""" -> she said "hi"
     *   - commas/newlines inside quotes (kept as text)
     * Small enough to read in one sitting; no external library needed.
     */
    static final class CsvReader implements AutoCloseable {
        private final BufferedReader in;
        private int pushback = -2;   // -2 means "nothing pushed back"

        CsvReader(Reader reader) {
            this.in = (reader instanceof BufferedReader b) ? b : new BufferedReader(reader);
        }

        /** The next record as a list of fields, or null at end of file. */
        List<String> next() throws IOException {
            List<String> fields = new ArrayList<>();
            StringBuilder field = new StringBuilder();
            boolean inQuotes = false;
            boolean sawAnything = false;
            int c;
            while ((c = read()) != -1) {
                sawAnything = true;
                if (inQuotes) {
                    if (c == '"') {
                        int next = read();
                        if (next == '"') field.append('"');      // "" -> one quote
                        else { inQuotes = false; pushback(next); } // closing quote
                    } else {
                        field.append((char) c);                  // comma/newline = text here
                    }
                } else if (c == '"') {
                    inQuotes = true;
                } else if (c == ',') {
                    fields.add(field.toString());
                    field.setLength(0);
                } else if (c == '\n') {
                    fields.add(field.toString());
                    return fields;                               // end of record
                } else if (c != '\r') {
                    field.append((char) c);
                }
            }
            if (!sawAnything) return null;                       // clean end of file
            fields.add(field.toString());
            return fields;
        }

        private int read() throws IOException {
            if (pushback != -2) { int v = pushback; pushback = -2; return v; }
            return in.read();
        }

        private void pushback(int c) { pushback = c; }

        @Override public void close() throws IOException { in.close(); }
    }
}
